# Generated by Django 5.1.4 on 2025-02-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default='00'),
            preserve_default=False,
        ),
    ]
